// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Ad struct {
	ID             pgtype.UUID      `db:"id" json:"id"`
	CampaignID     pgtype.UUID      `db:"campaign_id" json:"campaign_id"`
	Title          pgtype.Text      `db:"title" json:"title"`
	Description    pgtype.Text      `db:"description" json:"description"`
	ImageUrl       pgtype.Text      `db:"image_url" json:"image_url"`
	DestinationUrl pgtype.Text      `db:"destination_url" json:"destination_url"`
	CtaLabel       pgtype.Text      `db:"cta_label" json:"cta_label"`
	TargetingJson  []byte           `db:"targeting_json" json:"targeting_json"`
	Status         pgtype.Text      `db:"status" json:"status"`
	CreatedAt      pgtype.Timestamp `db:"created_at" json:"created_at"`
}

type AdCampaign struct {
	ID           pgtype.UUID      `db:"id" json:"id"`
	AdvertiserID pgtype.UUID      `db:"advertiser_id" json:"advertiser_id"`
	Name         string           `db:"name" json:"name"`
	Status       pgtype.Text      `db:"status" json:"status"`
	Budget       pgtype.Numeric   `db:"budget" json:"budget"`
	DailyBudget  pgtype.Numeric   `db:"daily_budget" json:"daily_budget"`
	StartDate    pgtype.Date      `db:"start_date" json:"start_date"`
	EndDate      pgtype.Date      `db:"end_date" json:"end_date"`
	CreatedAt    pgtype.Timestamp `db:"created_at" json:"created_at"`
}

type Advertiser struct {
	ID        pgtype.UUID      `db:"id" json:"id"`
	Name      string           `db:"name" json:"name"`
	Email     string           `db:"email" json:"email"`
	Balance   pgtype.Numeric   `db:"balance" json:"balance"`
	CreatedAt pgtype.Timestamp `db:"created_at" json:"created_at"`
}

type Auction struct {
	ID             pgtype.UUID      `db:"id" json:"id"`
	PlacementID    pgtype.UUID      `db:"placement_id" json:"placement_id"`
	RequestContext []byte           `db:"request_context" json:"request_context"`
	Timestamp      pgtype.Timestamp `db:"timestamp" json:"timestamp"`
}

type AuctionBid struct {
	ID        pgtype.UUID    `db:"id" json:"id"`
	AuctionID pgtype.UUID    `db:"auction_id" json:"auction_id"`
	BidID     pgtype.UUID    `db:"bid_id" json:"bid_id"`
	Price     pgtype.Numeric `db:"price" json:"price"`
	Score     pgtype.Numeric `db:"score" json:"score"`
	IsWinner  pgtype.Bool    `db:"is_winner" json:"is_winner"`
}

type Bid struct {
	ID            pgtype.UUID      `db:"id" json:"id"`
	AdID          pgtype.UUID      `db:"ad_id" json:"ad_id"`
	PlacementID   pgtype.UUID      `db:"placement_id" json:"placement_id"`
	BidPrice      pgtype.Numeric   `db:"bid_price" json:"bid_price"`
	MaxDailySpend pgtype.Numeric   `db:"max_daily_spend" json:"max_daily_spend"`
	CreatedAt     pgtype.Timestamp `db:"created_at" json:"created_at"`
}

type Click struct {
	ID           pgtype.UUID      `db:"id" json:"id"`
	ImpressionID pgtype.UUID      `db:"impression_id" json:"impression_id"`
	ClickedAt    pgtype.Timestamp `db:"clicked_at" json:"clicked_at"`
}

type Impression struct {
	ID          pgtype.UUID      `db:"id" json:"id"`
	AdID        pgtype.UUID      `db:"ad_id" json:"ad_id"`
	PlacementID pgtype.UUID      `db:"placement_id" json:"placement_id"`
	AuctionID   pgtype.UUID      `db:"auction_id" json:"auction_id"`
	UserContext []byte           `db:"user_context" json:"user_context"`
	Timestamp   pgtype.Timestamp `db:"timestamp" json:"timestamp"`
}

type Placement struct {
	ID          pgtype.UUID      `db:"id" json:"id"`
	Name        string           `db:"name" json:"name"`
	Description pgtype.Text      `db:"description" json:"description"`
	SlotSize    pgtype.Text      `db:"slot_size" json:"slot_size"`
	CreatedAt   pgtype.Timestamp `db:"created_at" json:"created_at"`
}

type Session struct {
	Token        pgtype.UUID      `db:"token" json:"token"`
	AdvertiserID pgtype.UUID      `db:"advertiser_id" json:"advertiser_id"`
	ExpiresAt    pgtype.Timestamp `db:"expires_at" json:"expires_at"`
	CreatedAt    pgtype.Timestamp `db:"created_at" json:"created_at"`
}
