// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AverageCTR(ctx context.Context) (pgtype.Numeric, error)
	CheckCampaignBelongsToAdvertiser(ctx context.Context, arg CheckCampaignBelongsToAdvertiserParams) (bool, error)
	CountActiveAds(ctx context.Context) (int64, error)
	CountClicks(ctx context.Context) (int64, error)
	CountImpressions(ctx context.Context) (int64, error)
	CreateAd(ctx context.Context, arg CreateAdParams) (Ad, error)
	CreateCampaign(ctx context.Context, arg CreateCampaignParams) (AdCampaign, error)
	CreateClick(ctx context.Context, arg CreateClickParams) (Click, error)
	CreateImpression(ctx context.Context, arg CreateImpressionParams) (Impression, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	DeleteSession(ctx context.Context, token pgtype.UUID) error
	GetActiveBidsForPlacement(ctx context.Context, placementID pgtype.UUID) ([]GetActiveBidsForPlacementRow, error)
	GetAdPerformanceAnalysis(ctx context.Context, advertiserID pgtype.UUID) ([]GetAdPerformanceAnalysisRow, error)
	GetAds(ctx context.Context) ([]Ad, error)
	GetAdsByCampaign(ctx context.Context, campaignID pgtype.UUID) ([]GetAdsByCampaignRow, error)
	GetAdvertiserByEmail(ctx context.Context, email string) (Advertiser, error)
	GetBudgetAlerts(ctx context.Context, advertiserID pgtype.UUID) ([]GetBudgetAlertsRow, error)
	GetCampaignByID(ctx context.Context, id pgtype.UUID) (AdCampaign, error)
	GetCampaignMetrics(ctx context.Context, id pgtype.UUID) ([]GetCampaignMetricsRow, error)
	GetCampaignPerformanceAnalysis(ctx context.Context, advertiserID pgtype.UUID) ([]GetCampaignPerformanceAnalysisRow, error)
	GetCampaignSpend(ctx context.Context, id pgtype.UUID) (interface{}, error)
	GetCampaignsByAdvertiser(ctx context.Context, advertiserID pgtype.UUID) ([]GetCampaignsByAdvertiserRow, error)
	GetLastImpressionByAdID(ctx context.Context, adID pgtype.UUID) (pgtype.UUID, error)
	GetOptimizationRecommendations(ctx context.Context, advertiserID pgtype.UUID) ([]GetOptimizationRecommendationsRow, error)
	GetSessionByToken(ctx context.Context, token pgtype.UUID) (pgtype.UUID, error)
	InsertAuction(ctx context.Context, arg InsertAuctionParams) (Auction, error)
	InsertAuctionBid(ctx context.Context, arg InsertAuctionBidParams) (AuctionBid, error)
	UpdateCampaign(ctx context.Context, arg UpdateCampaignParams) (AdCampaign, error)
	UpdateCampaignStatus(ctx context.Context, arg UpdateCampaignStatusParams) (AdCampaign, error)
}

var _ Querier = (*Queries)(nil)
